export default [
  { title: 'Inspection Added', data: 'inspectionDateCreated' },
  { title: 'Inspection Scheduled', data: 'inspectionDateScheduledHtml' },
  { title: 'Permit #', data: 'permitNumber' },
  { title: 'Inspection Passed', data: 'inspectionDatePassedHtml' },
  { title: 'Inspection Failed', data: 'inspectionDateFailedHtml' },
  { title: 'Inspector', data: 'inspectorName' },
  { title: 'Permit Starts', data: 'permitDateStarts' },
  { title: 'Permit Ends', data: 'permitDateEnds' },
  { title: 'Ticket ID', data: 'ticketId' },
  { title: 'Ticket Created', data: 'ticketDateCreated' },
  { title: 'Ticket Scheduled', data: 'ticketDateScheduled' },
  { title: 'Date Imported', data: 'ticketDateImported' },
  { title: 'Times Bumped', data: 'bumpedCount' },
  { title: 'Ticket Type', data: 'ticketType' },
  { title: 'Builder', data: 'builderName' },
  { title: 'Subdivision', data: 'subdivisionName' },
  { title: 'House Address', data: 'houseAddress' },
  { title: 'City', data: 'houseCity' },
  { title: 'Lot', data: 'houseLot' },
  { title: 'State', data: 'houseState' },
  { title: 'County', data: 'houseCounty' },
  { title: 'Zip', data: 'houseZip' },
  { title: 'Site Ready', data: 'ticketDateReady' },
  { title: 'Sent Out', data: 'ticketDateSentout' },
  { title: 'Supervisor', data: 'supervisorName' },
  { title: 'Plumber', data: 'plumberName' },
  { title: 'Helper', data: 'helperName' },
  { title: 'Payout', data: 'payoutTotal' },
  { title: 'Work Started', data: 'ticketDateStarted' },
  { title: 'Completed', data: 'ticketDateCompleted' },
  { title: 'Walked', data: 'ticketDateWalked' },
]
