export default [
  { title: 'Ticket ID', data: 'ticketId' },
  { title: 'Scheduled', data: 'ticketDateScheduledHtml' },
  { title: 'Sent Out', data: 'ticketDateSentoutHtml' },
  { title: 'Completed', data: 'ticketDateCompleted' },
  { title: 'Times Bumped', data: 'bumpedCount' },
  { title: 'Type', data: 'ticketType' },
  { title: 'Plumber', data: 'plumberNameHtml' },
  { title: 'Helper', data: 'helperNameHtml' },
  { title: 'Waiting On', data: 'siteReason' },
  { title: 'Ticket Created', data: 'ticketDateScheduled' },
  { title: 'Date Imported', data: 'ticketDateImported' },
  { title: 'Ticket Type', data: 'ticketType' },
  { title: 'Builder', data: 'builderName' },
  { title: 'Subdivision', data: 'subdivisionName' },
  { title: 'House Address', data: 'houseAddress' },
  { title: 'City', data: 'houseCity' },
  { title: 'Lot', data: 'houseLot' },
  { title: 'State', data: 'houseState' },
  { title: 'County', data: 'houseCounty' },
  { title: 'Zip', data: 'houseZip' },
  { title: 'Site Ready', data: 'ticketDateReady' },
  { title: 'Supervisor', data: 'supervisorName' },
  { title: 'Work Started', data: 'ticketDateStarted' },
  { title: 'Completed', data: 'ticketDateCompleted' },
  { title: 'Walked', data: 'ticketDateWalked' },
]
