export default [
  { title: 'Order ID', data: 'orderId' },
  { title: 'Order #', data: 'orderNumberHtml' },
  { title: 'Supplier', data: 'supplierName' },
  { title: 'Total ($)', data: 'totalCost' },
  { title: 'Item Count', data: 'itemCount' },
  { title: 'Date Ordered', data: 'dateOrdered' },
  { title: 'Date Received', data: 'receivedPercent' },
  { title: 'Ticket ID', data: 'ticketId' },
  { title: 'Ticket Created', data: 'ticketDateCreated' },
  { title: 'Ticket Scheduled', data: 'ticketDateScheduled' },
  { title: 'Date Imported', data: 'ticketDateImported' },
  { title: 'Ticket Type', data: 'ticketType' },
  { title: 'Builder', data: 'builderName' },
  { title: 'Subdivision', data: 'subdivisionName' },
  { title: 'House Address', data: 'houseAddress' },
  { title: 'City', data: 'houseCity' },
  { title: 'Lot', data: 'houseLot' },
  { title: 'State', data: 'houseState' },
  { title: 'County', data: 'houseCounty' },
  { title: 'Zip', data: 'houseZip' },
  { title: 'Site Ready', data: 'ticketDateReady' },
  { title: 'Sent Out', data: 'ticketDateSentout' },
  { title: 'Supervisor', data: 'supervisorName' },
  { title: 'Plumber', data: 'plumberName' },
  { title: 'Helper', data: 'helperName' },
  { title: 'Work Started', data: 'ticketDateStarted' },
  { title: 'Completed', data: 'ticketDateCompleted' },
  { title: 'Walked', data: 'ticketDateWalked' },
]
