INSERT INTO ticket_types
(ticket_type, requiresimport, requirespermit, requirespo, payout)
VALUES
('Rough In', false, false, false, 0),
('Sewer and Water', false, false, false, 0),
('Make Ready (Sewer)', false, false, false, 0),
('Make Ready (Rough In)', false, false, false, 0),
('Punch List (Rough In)', false, false, false, 0),
('Pull Ball (Sewer)', false, false, false, 0),
('Tub Set', false, false, false, 0),
('Make Ready (Tub Set)', false, false, false, 0),
('Punch List (Tub Set)', false, false, false, 0),
('Pull Ball (Tub Set)', false, false, false, 0),
('Trim', false, false, false, 0),
('Make Ready (Trim)', false, false, false, 0),
('Punch List (Trim)', false, false, false, 0),
('Water Meter Hookup', false, false, false, 0),
('Punch List', false, false, false, 0),
('Purchase Order', false, false, false, 0),
('Material Drop Off', false, false, false, 0),
('Time & Material', false, false, false, 0),
('Warranty', false, false, false, 0),
('Solar', false, false, false, 0),
('Misc', false, false, false, 0),
('Gas Underground', false, false, false, 0),
('Gas Top Out', false, false, false, 0),
('Gas Trim', false, false, false, 0),
('Service', false, false, false, 0);
