DROP TABLE IF EXISTS columns CASCADE;
CREATE TABLE columns (
  id serial NOT NULL,
  page varchar(64) NOT NULL,
  title varchar(64) NOT NULL,
  data varchar(64) NOT NULL,
  visible boolean DEFAULT true NOT NULL,
  PRIMARY KEY (id)
);
INSERT INTO columns (page, title, data, visible) VALUES
  ('tickets',       'Ticket ID',             'ticket_id',                     true),
  ('tickets',       'Ticket Created',        'ticket_date_created',           false),
  ('tickets',       'Ticket Scheduled',      'ticket_date_scheduled',         true),
  ('tickets',       'Date Imported',         'ticket_date_imported_html',     true),
  ('tickets',       'Times Bumped',          'bumped_count',                  false),
  ('tickets',       'Ticket Type',           'ticket_type',                   true),
  ('tickets',       'Builder',               'builder_name',                  true),
  ('tickets',       'Subdivision',           'subdivision_name',              true),
  ('tickets',       'House Address',         'house_address',                 false),
  ('tickets',       'City',                  'house_city',                    false),
  ('tickets',       'Lot',                   'house_lot',                     true),
  ('tickets',       'State',                 'house_state',                   false),
  ('tickets',       'County',                'house_county',                  false),
  ('tickets',       'Zip',                   'house_zip',                     false),
  ('tickets',       'Print',                 'print_ticket_html',             false),
  ('tickets',       'Site Ready',            'ticket_date_ready',             false),
  ('tickets',       'Sent Out',              'ticket_date_sentout',           false),
  ('tickets',       'Supervisor',            'supervisor_name',               false),
  ('tickets',       'Plumber',               'plumber_name',                  false),
  ('tickets',       'Helper',                'helper_name',                   false),
  ('tickets',       'Payout',                'payout_total',                  false),
  ('tickets',       'Work Started',          'ticket_date_started',           false),
  ('tickets',       'Completed',             'ticket_date_completed',         false),
  ('tickets',       'Walked',                'ticket_date_walked',            false),
-- billing unique
  ('billing',       'Total',                 'ticket_total_html',             true),
  ('billing',       'Billed',                'ticket_billed_html',            true),
  ('billing',       'Paid',                  'ticket_paid_html',              true),
  ('billing',       'Last Paid',             'ticket_lastpaid',               true),
  ('billing',       'Ticket ID',             'ticket_id',                     false),
  ('billing',       'Ticket Created',        'ticket_date_scheduled',         false),
  ('billing',       'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('billing',       'Date Imported',         'ticket_date_imported',          false),
  ('billing',       'Times Bumped',          'bumped_count',                  false),
  ('billing',       'Ticket Type',           'ticket_type',                   true),
  ('billing',       'Builder',               'builder_name',                  true),
  ('billing',       'Subdivision',           'subdivision_name',              true),
  ('billing',       'House Address',         'house_address',                 false),
  ('billing',       'City',                  'house_city',                    false),
  ('billing',       'Lot',                   'house_lot',                     true),
  ('billing',       'State',                 'house_state',                   false),
  ('billing',       'County',                'house_county',                  false),
  ('billing',       'Zip',                   'house_zip',                     false),
  ('billing',       'Site Ready',            'ticket_date_ready',             false),
  ('billing',       'Sent Out',              'ticket_date_sentout',           false),
  ('billing',       'Supervisor',            'supervisor_name',               false),
  ('billing',       'Plumber',               'plumber_name',                  false),
  ('billing',       'Helper',                'helper_name',                   false),
  ('billing',       'Payout',                'payout_total',                  false),
  ('billing',       'Work Started',          'ticket_date_started',           false),
  ('billing',       'Completed',             'ticket_date_completed',         true),
  ('billing',       'Walked',                'ticket_date_walked',            false),
  -- inspections unique
  ('inspections',   'Inspection Added',      'inspection_date_created',       true),
  ('inspections',   'Inspection Scheduled',  'inspection_date_scheduled_html',true),
  ('inspections',   'Permit #',              'permit_number',                 true),
  ('inspections',   'Inspection Passed',     'inspection_date_passed_html',   true),
  ('inspections',   'Inspection Failed',     'inspection_date_failed_html',   true),
  ('inspections',   'Inspector',             'inspector_name',                true),
  ('inspections',   'Permit Starts',         'permit_date_starts',            false),
  ('inspections',   'Permit Ends',           'permit_date_ends',              false),
  ('inspections',   'Ticket ID',             'ticket_id',                     false),
  ('inspections',   'Ticket Created',        'ticket_date_created',         false),
  ('inspections',   'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('inspections',   'Date Imported',         'ticket_date_imported',          false),
  ('inspections',   'Times Bumped',          'bumped_count',                  false),
  ('inspections',   'Ticket Type',           'ticket_type',                   true),
  ('inspections',   'Builder',               'builder_name',                  false),
  ('inspections',   'Subdivision',           'subdivision_name',              true),
  ('inspections',   'House Address',         'house_address',                 true),
  ('inspections',   'City',                  'house_city',                    true),
  ('inspections',   'Lot',                   'house_lot',                     true),
  ('inspections',   'State',                 'house_state',                   false),
  ('inspections',   'County',                'house_county',                  true),
  ('inspections',   'Zip',                   'house_zip',                     false),
  ('inspections',   'Site Ready',            'ticket_date_ready',             false),
  ('inspections',   'Sent Out',              'ticket_date_sentout',           true),
  ('inspections',   'Supervisor',            'supervisor_name',               false),
  ('inspections',   'Plumber',               'plumber_name',                  false),
  ('inspections',   'Helper',                'helper_name',                   false),
  ('inspections',   'Payout',                'payout_total',                  false),
  ('inspections',   'Work Started',          'ticket_date_started',           true),
  ('inspections',   'Completed',             'ticket_date_completed',         true),
  ('inspections',   'Walked',                'ticket_date_walked',            false),
  -- orders unique
  ('orders',        'Order ID',              'order_id',                      false),
  ('orders',        'Order #',               'order_number_html',             true),
  ('orders',        'Supplier',              'supplier_name',                 true),
  ('orders',        'Total ($)',             'total_cost',                    true),
  ('orders',        'Item Count',            'item_count',                    true),
  ('orders',        'Date Ordered',          'date_ordered',                  true),
  ('orders',        'Date Received',         'received_percent',              true),
  ('orders',        'Ticket ID',             'ticket_id',                     false),
  ('orders',        'Ticket Created',        'ticket_date_created',           false),
  ('orders',        'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('orders',        'Date Imported',         'ticket_date_imported',          false),
  ('orders',        'Ticket Type',           'ticket_type',                   true),
  ('orders',        'Builder',               'builder_name',                  true),
  ('orders',        'Subdivision',           'subdivision_name',              true),
  ('orders',        'House Address',         'house_address',                 false),
  ('orders',        'City',                  'house_city',                    false),
  ('orders',        'Lot',                   'house_lot',                     true),
  ('orders',        'State',                 'house_state',                   false),
  ('orders',        'County',                'house_county',                  false),
  ('orders',        'Zip',                   'house_zip',                     false),
  ('orders',        'Site Ready',            'ticket_date_ready',             false),
  ('orders',        'Sent Out',              'ticket_date_sentout',           false),
  ('orders',        'Supervisor',            'supervisor_name',               false),
  ('orders',        'Plumber',               'plumber_name',                  false),
  ('orders',        'Helper',                'helper_name',                   false),
  ('orders',        'Work Started',          'ticket_date_started',           false),
  ('orders',        'Completed',             'ticket_date_completed',         false),
  ('orders',        'Walked',                'ticket_date_walked',            false),
  -- permits unique
  ('permits',      'Permit #',               'permit_number',                 true),
  ('permits',      'Permit Starts',          'permit_date_starts',            true),
  ('permits',      'Permit Ends',            'permit_date_ends',              true),
  ('permits',      'Permit Valid',           'permit_valid',                  true),
  ('permits',       'Ticket ID',             'ticket_id',                     false),
  ('permits',       'Ticket Created',        'ticket_date_scheduled',         false),
  ('permits',       'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('permits',       'Date Imported',         'ticket_date_imported',          false),
  ('permits',       'Ticket Type',           'ticket_type',                   true),
  ('permits',       'Builder',               'builder_name',                  true),
  ('permits',       'Subdivision',           'subdivision_name',              true),
  ('permits',       'House Address',         'house_address',                 true),
  ('permits',       'City',                  'house_city',                    true),
  ('permits',       'Lot',                   'house_lot',                     true),
  ('permits',       'State',                 'house_state',                   false),
  ('permits',       'County',                'house_county',                  true),
  ('permits',       'Zip',                   'house_zip',                     true),
  ('permits',       'Site Ready',            'ticket_date_ready',             false),
  ('permits',       'Sent Out',              'ticket_date_sentout',           false),
  ('permits',       'Supervisor',            'supervisor_name',               false),
  ('permits',       'Plumber',               'plumber_name',                  false),
  ('permits',       'Helper',                'helper_name',                   false),
  ('permits',       'Work Started',          'ticket_date_started',           false),
  ('permits',       'Completed',             'ticket_date_completed',         false),
  ('permits',       'Walked',                'ticket_date_walked',            false),
  -- schedule unique
  ('schedule',      'Ticket ID',             'ticket_id',                     true),
  ('schedule',      'Scheduled',              'ticket_date_scheduled_html', true),
  ('schedule',      'Sent Out',              'ticket_date_sentout_html', true),
  ('schedule',      'Completed',              'ticket_date_completed', true),
  ('schedule',      'Times Bumped',              'bumped_count', true),
  ('schedule',      'Type',              'ticket_type', true),
  ('schedule',      'Plumber',              'plumber_name_html', true),
  ('schedule',      'Helper',              'helper_name_html', true),
  ('schedule',      'Waiting On',            'site_reason',                   false),
  ('schedule',      'Ticket Created',        'ticket_date_scheduled',         false),
  -- ('schedule',      'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('schedule',      'Date Imported',         'ticket_date_imported',          false),
  ('schedule',      'Ticket Type',           'ticket_type',                   true),
  ('schedule',      'Builder',               'builder_name',                  true),
  ('schedule',      'Subdivision',           'subdivision_name',              true),
  ('schedule',      'House Address',         'house_address',                 false),
  ('schedule',      'City',                  'house_city',                    true),
  ('schedule',      'Lot',                   'house_lot',                     true),
  ('schedule',      'State',                 'house_state',                   false),
  ('schedule',      'County',                'house_county',                  false),
  ('schedule',      'Zip',                   'house_zip',                     false),
  ('schedule',      'Site Ready',            'ticket_date_ready',             false),
  -- ('schedule',      'Sent Out',              'ticket_date_sentout',           false),
  ('schedule',      'Supervisor',            'supervisor_name',               false),
  -- ('schedule',      'Plumber',               'plumber_name',                  false),
  -- ('schedule',      'Helper',                'helper_name',                   false),
  ('schedule',      'Work Started',          'ticket_date_started',           false),
  ('schedule',      'Completed',             'ticket_date_completed',         false),
  ('schedule',      'Walked',                'ticket_date_walked',            false),
  -- sites unique
  ('sites',         'Ticket ID',             'ticket_id',                     true),
  ('sites',         'Waiting On',            'site_reason',                   true),
  ('sites',         'Site Ready',            'ticket_date_ready_html',        true),
  ('sites',         'Ticket Created',        'ticket_date_scheduled',         false),
  ('sites',         'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('sites',         'Date Imported',         'ticket_date_imported',          false),
  ('sites',         'Ticket Type',           'ticket_type',                   true),
  ('sites',         'Builder',               'builder_name',                  true),
  ('sites',         'Subdivision',           'subdivision_name',              true),
  ('sites',         'House Address',         'house_address',                 true),
  ('sites',         'City',                  'house_city',                    true),
  ('sites',         'Lot',                   'house_lot',                     true),
  ('sites',         'State',                 'house_state',                   false),
  ('sites',         'County',                'house_county',                  true),
  ('sites',         'Zip',                   'house_zip',                     true),
  ('sites',         'Sent Out',              'ticket_date_sentout',           false),
  ('sites',         'Supervisor',            'supervisor_name',               false),
  ('sites',         'Plumber',               'plumber_name',                  false),
  ('sites',         'Helper',                'helper_name',                   false),
  ('sites',         'Work Started',          'ticket_date_started',           true),
  ('sites',         'Completed',             'ticket_date_completed',         true),
  ('sites',         'Walked',                'ticket_date_walked',            false),
  -- wip unique
  ('wip',           'Started',               'ticket_date_started_html',      true),
  ('wip',           'Completed',             'ticket_date_completed_html',    true),
  ('wip',           'Walked',                'ticket_date_walked_html',       true),
  ('wip',           'Ticket ID',             'ticket_id',                     false),
  ('wip',           'Ticket Created',        'ticket_date_scheduled',         false),
  ('wip',           'Ticket Scheduled',      'ticket_date_scheduled',         false),
  ('wip',           'Date Imported',         'ticket_date_imported',          false),
  ('wip',           'Ticket Type',           'ticket_type',                   true),
  ('wip',           'Builder',               'builder_name',                  true),
  ('wip',           'Subdivision',           'subdivision_name',              true),
  ('wip',           'House Address',         'house_address',                 true),
  ('wip',           'City',                  'house_city',                    true),
  ('wip',           'Lot',                   'house_lot',                     true),
  ('wip',           'State',                 'house_state',                   false),
  ('wip',           'County',                'house_county',                  true),
  ('wip',           'Zip',                   'house_zip',                     true),
  ('wip',           'Site Ready',            'ticket_date_ready',             false),
  ('wip',           'Sent Out',              'ticket_date_sentout',           false),
  ('wip',           'Supervisor',            'supervisor_name',               false),
  ('wip',           'Plumber',               'plumber_name',                  false),
  ('wip',           'Helper',                'helper_name',                   false),
  ('wip',           'Work Started',          'ticket_date_started',           false),
  ('wip',           'Completed',             'ticket_date_completed',         false),
  ('wip',           'Walked',                'ticket_date_walked',            false);


DROP TABLE IF EXISTS user_columns CASCADE;
CREATE TABLE user_columns (
  user_id int REFERENCES users(id) NOT NULL,
  column_id int REFERENCES columns(id) NOT NULL,
  visible boolean NOT NULL,
  UNIQUE(user_id, column_id)
);
