export default [
  { title: 'Ticket ID', data: 'ticketId' },
  { title: 'Ticket Created', data: 'ticketDateCreatedFormatted' },
  { title: 'Ticket Scheduled', data: 'ticketDateScheduledFormatted' },
  { title: 'Date Imported', data: 'ticketDateImportedHtml' },
  { title: 'Times Bumped', data: 'bumpedCount' },
  { title: 'Ticket Type', data: 'ticketType' },
  { title: 'Builder', data: 'builderName' },
  { title: 'Subdivision', data: 'subdivisionName' },
  { title: 'House Address', data: 'houseAddress' },
  { title: 'City', data: 'houseCity' },
  { title: 'Lot', data: 'houseLot' },
  { title: 'State', data: 'houseState' },
  { title: 'County', data: 'houseCounty' },
  { title: 'Zip', data: 'houseZip' },
  { title: 'Print', data: 'printTicketHtml' },
  { title: 'Site Ready', data: 'ticketDateReadyFormatted' },
  { title: 'Sent Out', data: 'ticketDateSentout' },
  { title: 'Supervisor', data: 'supervisorName' },
  { title: 'Plumber', data: 'plumberName' },
  { title: 'Helper', data: 'helperName' },
  { title: 'Payout', data: 'payoutTotal' },
  { title: 'Work Started', data: 'ticketDateStartedFormatted' },
  { title: 'Completed', data: 'ticketDateCompletedFormatted' },
  { title: 'Walked', data: 'ticketDateWalkedFormatted' }
]
